/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;


import data.*;
import entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author diego
 */
public class GestionInscripcion extends javax.swing.JInternalFrame {
    
    private Conexion con = new Conexion("jdbc:mariadb://localhost:3306/proyecto_transversal", "root", "");
    private Alumno_data ad = new Alumno_data(con);
    private Materia_data md = new Materia_data(con);
    private Inscripcion_data id = new Inscripcion_data(con);
    private Alumno a = new Alumno();
    
    
    
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int col){ 
            return false;
        }
    };
    /**
     * Creates new form GestionInscripcion
     */
    public GestionInscripcion() {
        initComponents();
        cargarCabeceraLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbMati = new javax.swing.JRadioButton();
        jrbMatni = new javax.swing.JRadioButton();
        jtDni = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListamat = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbDesinscribir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Inscripción a Materias");

        jSeparator1.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Documento alumno:");

        jLabel2.setText("Listado de materias");

        jrbMati.setText("Materias Inscriptas");
        jrbMati.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbMatiItemStateChanged(evt);
            }
        });

        jrbMatni.setText("Materias no Inscriptas");
        jrbMatni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbMatniItemStateChanged(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Alumno:");

        jlAlumno.setText("-");

        jSeparator2.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(255, 204, 204));

        jtListamat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtListamat);

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbDesinscribir.setText("Anular Inscripcion");
        jbDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesinscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtDni)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlAlumno)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jrbMati)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbMatni))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jbInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDesinscribir)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlAlumno))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMati)
                    .addComponent(jrbMatni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbDesinscribir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        
        try {
            a = ad.buscarAlumnoPorDni(Integer.parseInt(jtDni.getText()));
            if (a == null) {
                JOptionPane.showMessageDialog(this, "No hay ningun alumno con ese DNI.");
            } else {                
                jlAlumno.setText(a.getApellido()+ " " +a.getNombre());
                jrbMati.setSelected(true);
            }
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI correctamente.");
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesinscribirActionPerformed
        String mat = modelo.getValueAt(jtListamat.getSelectedRow(), 0).toString();
            
        id.eliminarInscripcion(Integer.parseInt(jtDni.getText()),mat);
        cargarListaMI();
        
    }//GEN-LAST:event_jbDesinscribirActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        String mat = modelo.getValueAt(jtListamat.getSelectedRow(), 0).toString();
        Materia materia = md.buscarMateria(mat);
        
        id.inscribirAlumno(a, materia);
        cargarListaMNI();
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jrbMatiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbMatiItemStateChanged
        
        if (jrbMati.isSelected()) {
            jrbMatni.setSelected(false);
            jbInscribir.setEnabled(false);
            jbDesinscribir.setEnabled(true);
            
            cargarListaMI();               
        }
        if (jrbMati.isSelected() == false){
            jrbMatni.setSelected(true);
            
        }
        
             
    }//GEN-LAST:event_jrbMatiItemStateChanged

    private void jrbMatniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbMatniItemStateChanged
        
        if (jrbMatni.isSelected()) {
            jrbMati.setSelected(false);
            jbDesinscribir.setEnabled(false);
            jbInscribir.setEnabled(true);
            
            cargarListaMNI();
        }
        if (jrbMatni.isSelected() == false){
            jrbMati.setSelected(true);
            
        }       
        
    }//GEN-LAST:event_jrbMatniItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDesinscribir;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JRadioButton jrbMati;
    private javax.swing.JRadioButton jrbMatni;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTable jtListamat;
    // End of variables declaration//GEN-END:variables

    public void cargarCabeceraLista(){ //agrego nombre a las columnas y cargo el modelo
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");        
        jtListamat.setModel(modelo);
    }
    
    public void cargarListaMI(){
        List<Inscripcion> listamat = new ArrayList<>();
        
        listamat = id.listarInscripcionesPorAlumno(a.getDni());        
        
        
        //MODIFICACION DE TABLA
        modelo.setRowCount(0); //borra la tabla
        for(Inscripcion insc:listamat){//carga la tabla                              
            modelo.addRow(new Object[]{
                insc.getId_materia().getNombre(),
                insc.getId_materia().getAnio()
            });                   
        }   
    }
    
    public void cargarListaMNI(){
        List<Materia> listamat = new ArrayList<>();

        listamat = id.listarMateriasNOCursadasPorAlumno(Integer.parseInt(jtDni.getText()));

        //MODIFICACION DE TABLA
        modelo.setRowCount(0); //borra la tabla
        for (Materia mat : listamat) {//carga la tabla                              
            modelo.addRow(new Object[]{
                mat.getNombre(),
                mat.getAnio()
            });
        }
    }
    

}
